stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker build -t todo-list-app .

test:
  stage: test
  script:
    - npm install
    - npm test

deploy:
  stage: deploy
  script:
    - docker-compose up -d